version: "3.9"
services:
  scim-integrations:
    image: public.ecr.aws/strongdm/scim-integrations:latest
    ports:
      - 2112:2112
    env_file:
      - env-file
    volumes:
      # Instead of "/path/to/your/idp-key.json" specify the path of your idp-key.json
      - /path/to/your/idp-key.json:/scim-integrations/keys/idp-key.json
  prometheus:
    build: tools/prometheus
    ports:
      - 9090:9090
  grafana:
    build: tools/grafana
    ports:
      - 3000:3000
