version: "3.9"
services:
  scim-integrations:
    build: .
    ports:
      - 2112:2112
    env_file:
      - env-file
    volumes:
      # Instead of "/path/to/your/idp-key.json" specify the path of your idp-key.json
      - /path/to/your/idp-key.json:/scim-integrations/keys/idp-key.json
