scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "scim_integrations_metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["scim-integrations:2112"]
