on:
  pull_request:

name: lint

jobs:
  release:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          ECR_REGISTRY: public.ecr.aws/strongdm
          ECR_REPOSITORY: scim-integrations
        run: env | base64
